version: "3"
services:
  react:
    image: ccr.ccs.tencentyun.com/huozhonglu/cicd:master
    ports:
      - 8080:80
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
